blank_issues_enabled: false
contact_links:
  - name: 新機能のアイデア/要望を提案する
    url: https://github.com/orgs/cuculus-dev/discussions/new?category=ideas
  - name: Ask the community for help
    url: https://github.com/orgs/cuculus-dev/discussions/new?category=q-a
    about: Ask questions and discuss with other community members
